export const raceResultsColumns = [
  { name: '#', id: 0 },
  { name: 'Кат', id: 1 },
  { name: '', id: 2 },
  { name: 'Райдер', id: 3 },
  { name: 'Время', id: 4 },
  { name: 'Отс.', id: 5 },
  { name: 'Отс.пр.', id: 6 },
  { name: 'Сред.', id: 7 },
  { name: '', id: 8 },
  { name: '5с', id: 9 },
  { name: '30с', id: 10 },
  { name: '1м', id: 11 },
  { name: '5м', id: 12 },
  { name: '12м', id: 13 },
  { name: '20м', id: 14 },
  { name: '40м', id: 15 },
  { name: 'Пульс', id: 16 },
  { name: 'Вес', id: 17 },
  { name: 'Рост', id: 18 },
  { name: 'Возр.', id: 19 },
];
