export const stageClear = {
	_id: 'none',
	number: '',
	dateStart: Date.now(),
	route: '',
	routeLink: '',
	world: '',
	laps: '',
	distance: '',
	ascent: '',
	type: '',
	quantitySprints: '',
	quantityMountains: '',
	needCount: true,
	hasResults: false,
};
